/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import CONTROL.Validacion;
import CONTROL.ValidacionUsuario;
import java.sql.Connection;
import java.awt.Dimension;
import MODELO.ConexionDB;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import javax.swing.JFrame;


/**
 *
 * @author ALEJANDRO
 */
public class Login extends javax.swing.JFrame {
    Validacion val = new Validacion();

    /**
     * Creates new form VistaLogin
     */
    private boolean contraseñaVisible = false;
    
    public Login() {
        initComponents();
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Login- SISTEMA DE LA INSTITUCIÓN");
        this.setSize(new Dimension (550, 560));
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnIngreso = new javax.swing.JButton();
        txtContraseña = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        btnUnir1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbOjo = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblObligatorio1 = new javax.swing.JLabel();
        lblObligatorio2 = new javax.swing.JLabel();
        lbOjo1 = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        cmbTipoUsuario = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(350, 500));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(401, 186, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setActionCommand("<Not Set>");
        txtUsuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUsuarioFocusLost(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtUsuarioKeyTyped(evt);
            }
        });
        jPanel4.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 211, 32));
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 247, -1, 32));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Elija su Usuario");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 211, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Contraseña");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 211, -1));

        btnIngreso.setBackground(new java.awt.Color(255, 153, 0));
        btnIngreso.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnIngreso.setText("Iniciar sesión");
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        jPanel4.add(btnIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 211, 32));

        txtContraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtContraseña.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaFocusLost(evt);
            }
        });
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        jPanel4.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 211, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("¿No tiene una cuenta?");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));

        btnUnir1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnUnir1.setForeground(new java.awt.Color(255, 153, 0));
        btnUnir1.setText("Regístrate");
        btnUnir1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnUnir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnir1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnUnir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 229, -1, -1));
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 304, -1, 22));
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        lbOjo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOjoMouseClicked(evt);
            }
        });
        jPanel4.add(lbOjo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 30, 30));

        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 30, 30));

        lblObligatorio1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblObligatorio1.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio1.setText("*obligatorio");
        jPanel4.add(lblObligatorio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, -1, -1));

        lblObligatorio2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        lblObligatorio2.setForeground(new java.awt.Color(204, 0, 51));
        lblObligatorio2.setText("*obligatorio");
        jPanel4.add(lblObligatorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, -1));

        lbOjo1.setText("OJITO");
        lbOjo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbOjo1MouseClicked(evt);
            }
        });
        jPanel4.add(lbOjo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, 50));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Hope logo 13.png"))); // NOI18N
        jPanel4.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 210, 120));

        cmbTipoUsuario.setForeground(new java.awt.Color(153, 153, 153));
        cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo de usuario", "Administrador", "Profesor", "Alumno" }));
        jPanel4.add(cmbTipoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 150, 30));

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Correo Electrónico");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 211, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 500, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 542, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsuarioFocusLost
        // TODO add your handling code here:
        if(txtUsuario.getText().trim().isEmpty()){
            lblObligatorio1.setVisible(true);
        }else{
            lblObligatorio1.setVisible(false);
        }
    }//GEN-LAST:event_txtUsuarioFocusLost

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        //leerArchivo();
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioKeyTyped

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        // Obtener los valores de los campos
    String correo = txtUsuario.getText();
    String contrasena = new String(txtContraseña.getPassword());
    String tipoUsuario = (String) cmbTipoUsuario.getSelectedItem();

    // Validar campos no vacíos
    if (!ValidacionUsuario.camposNoVacios(correo, contrasena)) {
        JOptionPane.showMessageDialog(this, "El correo y la contraseña no pueden estar vacíos.");
        return;
    }

    // Validar formato de correo
    if (!ValidacionUsuario.valCorreo(correo)) {
        JOptionPane.showMessageDialog(this, "El correo electrónico no tiene un formato válido.");
        return;
    }

    // Validar contraseña
    if (!ValidacionUsuario.valContraseña(contrasena)) {
        JOptionPane.showMessageDialog(this, "La contraseña debe tener al menos 6 caracteres.");
        return;
    }

    // Validar tipo de usuario
    if (!ValidacionUsuario.tipoUsuarioValido(tipoUsuario)) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un tipo de usuario.");
        return;
    }

    Connection con = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        con = (Connection) ConexionDB.conectar();
        if (con == null) {
            JOptionPane.showMessageDialog(this, "No se pudo establecer conexión con la base de datos.");
            return;
        }

        String sql = "SELECT * FROM usuarios WHERE correo = ? AND contrasena = ? AND tipo_usuario = ?";
        stmt = con.prepareStatement(sql);
        stmt.setString(1, correo);
        stmt.setString(2, contrasena);
        stmt.setString(3, tipoUsuario);

        rs = stmt.executeQuery();
        
if (rs.next()) {
    switch (tipoUsuario) {
        case "Profesor" -> {
            // Obtener el ID del usuario logueado
            int idUsuario = rs.getInt("id");

            // Consultar el ID del profesor asociado a este usuario
            int idProfesor = getIdProfesor(idUsuario);

            if (idProfesor != -1) {
                // Abrir la vista del horario del profesor
                VPPaginaPrincipalProf profesor = new VPPaginaPrincipalProf();
            profesor.setVisible(true);
            this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un profesor asociado a este usuario.");
            }
        }
        case "Administrador" -> {
            VAdmPaginaPrincipalAdmin admin = new VAdmPaginaPrincipalAdmin();
            admin.setVisible(true);
            this.dispose();
        }
        case "Alumno" -> {
            VAlPaginaPrincipalAlumno alumno = new VAlPaginaPrincipalAlumno();
            alumno.setVisible(true);
            this.dispose();
        }
        default -> JOptionPane.showMessageDialog(this, "Tipo de usuario no reconocido.");
    }
} else {
    JOptionPane.showMessageDialog(this, "Correo o contraseña incorrectos.");
}
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al iniciar sesión: " + e.getMessage());
    } finally {
        // Cerrar recursos
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (con != null) ConexionDB.cerrarConexion((java.sql.Connection) con);
        } catch (SQLException ex) {
            System.out.println("Error al cerrar recursos: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void txtContraseñaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaFocusLost
        // TODO add your handling code here:
        if(val.valContraseña(new String(txtContraseña.getPassword()))){
            lblObligatorio2.setVisible(false);
        }else{
            lblObligatorio2.setVisible(true);
        }
    }//GEN-LAST:event_txtContraseñaFocusLost

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed

    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnUnir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnir1ActionPerformed
        NuevoUsuario ventanaRegistro = new NuevoUsuario();
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_btnUnir1ActionPerformed

    private void lbOjoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOjoMouseClicked
        // TODO add your handling code here:

        if (contraseñaVisible) {
            txtContraseña.setEchoChar('*');
        } else {
            txtContraseña.setEchoChar((char) 0);
        }
        contraseñaVisible = !contraseñaVisible;
    }//GEN-LAST:event_lbOjoMouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void lbOjo1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbOjo1MouseClicked
        // TODO add your handling code here:

        if (contraseñaVisible) {
            txtContraseña.setEchoChar('*');
        } else {
            txtContraseña.setEchoChar((char) 0);
        }
        contraseñaVisible = !contraseñaVisible;
    }//GEN-LAST:event_lbOjo1MouseClicked
/**
 * Obtiene el ID del profesor asociado al usuario logueado.
 * 
 * @param idUsuario El ID del usuario logueado.
 * @return El ID del profesor, o -1 si no se encuentra.
 */
private int getIdProfesor(int idUsuario) {
    Connection con = null;
    PreparedStatement stmt = null;
    ResultSet rs = null;

    try {
        con = ConexionDB.conectar();
        String query = "SELECT id FROM profesores WHERE id_usuario = ?";
        stmt = con.prepareStatement(query);
        stmt.setInt(1, idUsuario);

        rs = stmt.executeQuery();
        if (rs.next()) {
            return rs.getInt("id");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al obtener el ID del profesor: " + e.getMessage());
    } finally {
        try {
            if (rs != null) rs.close();
            if (stmt != null) stmt.close();
            if (con != null) ConexionDB.cerrarConexion(con);
        } catch (SQLException ex) {
            System.out.println("Error al cerrar recursos: " + ex.getMessage());
        }
    }
    return -1; // Retorna -1 si no se encuentra el profesor
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngreso;
    private javax.swing.JButton btnUnir1;
    private javax.swing.JComboBox<String> cmbTipoUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbOjo;
    private javax.swing.JLabel lbOjo1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblObligatorio1;
    private javax.swing.JLabel lblObligatorio2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
