/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Denis Peralta
 */
public class VAlHorarioAlumno extends javax.swing.JFrame {

    /**
     * Creates new form VAlHorarioAlumno
     */
    public VAlHorarioAlumno() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnImprimir1 = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        btnGrupo = new javax.swing.JButton();
        btnTarea = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        btnTarea1 = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblInstrucciones = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        txtLunes1 = new javax.swing.JTextField();
        lblInstrucciones1 = new javax.swing.JLabel();
        txtMartes1 = new javax.swing.JTextField();
        lblInstrucciones2 = new javax.swing.JLabel();
        txtMiercoles1 = new javax.swing.JTextField();
        lblInstrucciones3 = new javax.swing.JLabel();
        txtJueves1 = new javax.swing.JTextField();
        lblInstrucciones4 = new javax.swing.JLabel();
        txtViernes1 = new javax.swing.JTextField();
        lblInstrucciones5 = new javax.swing.JLabel();
        txtSabado1 = new javax.swing.JTextField();
        txtLunes6 = new javax.swing.JTextField();
        txtLunes3 = new javax.swing.JTextField();
        txtLunes4 = new javax.swing.JTextField();
        txtLunes5 = new javax.swing.JTextField();
        txtLunes7 = new javax.swing.JTextField();
        txtLunes2 = new javax.swing.JTextField();
        txtMartes2 = new javax.swing.JTextField();
        txtMartes3 = new javax.swing.JTextField();
        txtMartes4 = new javax.swing.JTextField();
        txtMartes5 = new javax.swing.JTextField();
        txtMartes6 = new javax.swing.JTextField();
        txtMartes7 = new javax.swing.JTextField();
        txtMiercoles2 = new javax.swing.JTextField();
        txtMiercoles3 = new javax.swing.JTextField();
        txtMiercoles4 = new javax.swing.JTextField();
        txtMiercoles5 = new javax.swing.JTextField();
        txtMiercoles6 = new javax.swing.JTextField();
        txtMiercoles7 = new javax.swing.JTextField();
        txtJueves2 = new javax.swing.JTextField();
        txtJueves3 = new javax.swing.JTextField();
        txtJueves4 = new javax.swing.JTextField();
        txtJueves5 = new javax.swing.JTextField();
        txtJueves6 = new javax.swing.JTextField();
        txtJueves7 = new javax.swing.JTextField();
        txtViernes2 = new javax.swing.JTextField();
        txtViernes3 = new javax.swing.JTextField();
        txtViernes4 = new javax.swing.JTextField();
        txtViernes5 = new javax.swing.JTextField();
        txtViernes6 = new javax.swing.JTextField();
        txtViernes7 = new javax.swing.JTextField();
        txtSabado2 = new javax.swing.JTextField();
        txtSabado3 = new javax.swing.JTextField();
        txtSabado4 = new javax.swing.JTextField();
        txtSabado5 = new javax.swing.JTextField();
        txtSabado6 = new javax.swing.JTextField();
        txtSabado7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImprimir1.setBackground(new java.awt.Color(204, 204, 204));
        btnImprimir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Volver.png"))); // NOI18N
        btnImprimir1.setText("Volver");
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 140, 30));

        btnCerrarSesion.setBackground(new java.awt.Color(178, 226, 226));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 180, 40));

        btnGrupo.setBackground(new java.awt.Color(178, 226, 226));
        btnGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/GrupoUsuario.png"))); // NOI18N
        btnGrupo.setText("Grupo");
        btnGrupo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 180, 40));

        btnTarea.setBackground(new java.awt.Color(178, 226, 226));
        btnTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/UserCircle.png"))); // NOI18N
        btnTarea.setText("Cuenta");
        btnTarea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 180, 40));

        btnMateria.setBackground(new java.awt.Color(178, 226, 226));
        btnMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Materia.png"))); // NOI18N
        btnMateria.setText("Materia");
        btnMateria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 180, 40));

        btnHorario.setBackground(new java.awt.Color(178, 226, 226));
        btnHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Calendario.png"))); // NOI18N
        btnHorario.setText("Horario");
        btnHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 180, 40));

        btnTarea1.setBackground(new java.awt.Color(178, 226, 226));
        btnTarea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Tarea.png"))); // NOI18N
        btnTarea1.setText("Tarea");
        btnTarea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarea1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 180, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Hope logo 13.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("HORARIO");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        lblInstrucciones.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones.setText("Lunes");
        getContentPane().add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, -1, 20));

        btnImprimir.setBackground(new java.awt.Color(204, 204, 204));
        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Document Check.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 580, 140, 30));

        txtLunes1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes1.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 120, 50));

        lblInstrucciones1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones1.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones1.setText("Martes");
        getContentPane().add(lblInstrucciones1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, 20));

        txtMartes1.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, 50));

        lblInstrucciones2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones2.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones2.setText("Miércoles");
        getContentPane().add(lblInstrucciones2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, 20));

        txtMiercoles1.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 50));

        lblInstrucciones3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones3.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones3.setText("Jueves");
        getContentPane().add(lblInstrucciones3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, 20));

        txtJueves1.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 120, 50));

        lblInstrucciones4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones4.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones4.setText("Viernes");
        getContentPane().add(lblInstrucciones4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, -1, 20));

        txtViernes1.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 150, 120, 50));

        lblInstrucciones5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones5.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones5.setText("Sábado");
        getContentPane().add(lblInstrucciones5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, -1, 20));

        txtSabado1.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 120, 50));

        txtLunes6.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes6.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 120, 50));

        txtLunes3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes3.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, 50));

        txtLunes4.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes4.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 120, 50));

        txtLunes5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes5.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 120, 50));

        txtLunes7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes7.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 120, 50));

        txtLunes2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        txtLunes2.setForeground(new java.awt.Color(204, 204, 204));
        txtLunes2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtLunes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLunes2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtLunes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, 50));

        txtMartes2.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 120, 50));

        txtMartes3.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 120, 50));

        txtMartes4.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 120, 50));

        txtMartes5.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 120, 50));

        txtMartes6.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 120, 50));

        txtMartes7.setForeground(new java.awt.Color(204, 204, 204));
        txtMartes7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMartes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMartes7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMartes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 120, 50));

        txtMiercoles2.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 120, 50));

        txtMiercoles3.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 120, 50));

        txtMiercoles4.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, 120, 50));

        txtMiercoles5.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, 120, 50));

        txtMiercoles6.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 450, 120, 50));

        txtMiercoles7.setForeground(new java.awt.Color(204, 204, 204));
        txtMiercoles7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtMiercoles7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMiercoles7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtMiercoles7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 510, 120, 50));

        txtJueves2.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 120, 50));

        txtJueves3.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 120, 50));

        txtJueves4.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, 120, 50));

        txtJueves5.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 120, 50));

        txtJueves6.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, 120, 50));

        txtJueves7.setForeground(new java.awt.Color(204, 204, 204));
        txtJueves7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtJueves7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJueves7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtJueves7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 120, 50));

        txtViernes2.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 120, 50));

        txtViernes3.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 270, 120, 50));

        txtViernes4.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 120, 50));

        txtViernes5.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 120, 50));

        txtViernes6.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, 120, 50));

        txtViernes7.setForeground(new java.awt.Color(204, 204, 204));
        txtViernes7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtViernes7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViernes7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtViernes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 120, 50));

        txtSabado2.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 210, 120, 50));

        txtSabado3.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 270, 120, 50));

        txtSabado4.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado4ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 120, 50));

        txtSabado5.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado5ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 120, 50));

        txtSabado6.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado6ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 450, 120, 50));

        txtSabado7.setForeground(new java.awt.Color(204, 204, 204));
        txtSabado7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        txtSabado7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSabado7ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSabado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 510, 120, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupoActionPerformed

    private void btnTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTareaActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnTarea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarea1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTarea1ActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void txtLunes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes1ActionPerformed

    private void txtMartes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes1ActionPerformed

    private void txtMiercoles1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles1ActionPerformed

    private void txtJueves1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves1ActionPerformed

    private void txtViernes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes1ActionPerformed

    private void txtSabado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado1ActionPerformed

    private void txtLunes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes6ActionPerformed

    private void txtLunes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes3ActionPerformed

    private void txtLunes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes4ActionPerformed

    private void txtLunes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes5ActionPerformed

    private void txtLunes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes7ActionPerformed

    private void txtLunes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLunes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLunes2ActionPerformed

    private void txtMartes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes2ActionPerformed

    private void txtMartes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes3ActionPerformed

    private void txtMartes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes4ActionPerformed

    private void txtMartes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes5ActionPerformed

    private void txtMartes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes6ActionPerformed

    private void txtMartes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMartes7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMartes7ActionPerformed

    private void txtMiercoles2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles2ActionPerformed

    private void txtMiercoles3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles3ActionPerformed

    private void txtMiercoles4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles4ActionPerformed

    private void txtMiercoles5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles5ActionPerformed

    private void txtMiercoles6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles6ActionPerformed

    private void txtMiercoles7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMiercoles7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMiercoles7ActionPerformed

    private void txtJueves2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves2ActionPerformed

    private void txtJueves3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves3ActionPerformed

    private void txtJueves4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves4ActionPerformed

    private void txtJueves5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves5ActionPerformed

    private void txtJueves6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves6ActionPerformed

    private void txtJueves7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJueves7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJueves7ActionPerformed

    private void txtViernes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes2ActionPerformed

    private void txtViernes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes3ActionPerformed

    private void txtViernes4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes4ActionPerformed

    private void txtViernes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes5ActionPerformed

    private void txtViernes6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes6ActionPerformed

    private void txtViernes7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViernes7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViernes7ActionPerformed

    private void txtSabado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado2ActionPerformed

    private void txtSabado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado3ActionPerformed

    private void txtSabado4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado4ActionPerformed

    private void txtSabado5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado5ActionPerformed

    private void txtSabado6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado6ActionPerformed

    private void txtSabado7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSabado7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSabado7ActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPHorarioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPHorarioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPHorarioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPHorarioProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAlHorarioAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnGrupo;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnMateria;
    private javax.swing.JButton btnTarea;
    private javax.swing.JButton btnTarea1;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblInstrucciones1;
    private javax.swing.JLabel lblInstrucciones2;
    private javax.swing.JLabel lblInstrucciones3;
    private javax.swing.JLabel lblInstrucciones4;
    private javax.swing.JLabel lblInstrucciones5;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtJueves1;
    private javax.swing.JTextField txtJueves2;
    private javax.swing.JTextField txtJueves3;
    private javax.swing.JTextField txtJueves4;
    private javax.swing.JTextField txtJueves5;
    private javax.swing.JTextField txtJueves6;
    private javax.swing.JTextField txtJueves7;
    private javax.swing.JTextField txtLunes1;
    private javax.swing.JTextField txtLunes2;
    private javax.swing.JTextField txtLunes3;
    private javax.swing.JTextField txtLunes4;
    private javax.swing.JTextField txtLunes5;
    private javax.swing.JTextField txtLunes6;
    private javax.swing.JTextField txtLunes7;
    private javax.swing.JTextField txtMartes1;
    private javax.swing.JTextField txtMartes2;
    private javax.swing.JTextField txtMartes3;
    private javax.swing.JTextField txtMartes4;
    private javax.swing.JTextField txtMartes5;
    private javax.swing.JTextField txtMartes6;
    private javax.swing.JTextField txtMartes7;
    private javax.swing.JTextField txtMiercoles1;
    private javax.swing.JTextField txtMiercoles2;
    private javax.swing.JTextField txtMiercoles3;
    private javax.swing.JTextField txtMiercoles4;
    private javax.swing.JTextField txtMiercoles5;
    private javax.swing.JTextField txtMiercoles6;
    private javax.swing.JTextField txtMiercoles7;
    private javax.swing.JTextField txtSabado1;
    private javax.swing.JTextField txtSabado2;
    private javax.swing.JTextField txtSabado3;
    private javax.swing.JTextField txtSabado4;
    private javax.swing.JTextField txtSabado5;
    private javax.swing.JTextField txtSabado6;
    private javax.swing.JTextField txtSabado7;
    private javax.swing.JTextField txtViernes1;
    private javax.swing.JTextField txtViernes2;
    private javax.swing.JTextField txtViernes3;
    private javax.swing.JTextField txtViernes4;
    private javax.swing.JTextField txtViernes5;
    private javax.swing.JTextField txtViernes6;
    private javax.swing.JTextField txtViernes7;
    // End of variables declaration//GEN-END:variables
}
