/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import javax.swing.JFrame;

/**
 *
 * @author Denis Peralta
 */
public class VAlPaginaPrincipalAlumno extends javax.swing.JFrame {

    /**
     * Creates new form InicioAlumno
     */
    public VAlPaginaPrincipalAlumno() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JButton();
        btnProfesores = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        btnTarea1 = new javax.swing.JButton();
        btnCalificaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Hope logo 13.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/iPad.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 820, -1));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("BIENVENIDO ALUMNO");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        btnCerrarSesion.setBackground(new java.awt.Color(178, 226, 226));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 180, 40));

        btnProfesores.setBackground(new java.awt.Color(178, 226, 226));
        btnProfesores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/UserCircle.png"))); // NOI18N
        btnProfesores.setText("Profesores");
        btnProfesores.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesoresActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 180, 40));

        btnMateria.setBackground(new java.awt.Color(178, 226, 226));
        btnMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Materia.png"))); // NOI18N
        btnMateria.setText("Materia");
        btnMateria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 180, 40));

        btnHorario.setBackground(new java.awt.Color(178, 226, 226));
        btnHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Calendario.png"))); // NOI18N
        btnHorario.setText("Horario");
        btnHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, 40));

        btnTarea1.setBackground(new java.awt.Color(178, 226, 226));
        btnTarea1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Tarea.png"))); // NOI18N
        btnTarea1.setText("Entregar Tareas");
        btnTarea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarea1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarea1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarea1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 180, 40));

        btnCalificaciones.setBackground(new java.awt.Color(178, 226, 226));
        btnCalificaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Document Check.png"))); // NOI18N
        btnCalificaciones.setText("Calificaciones");
        btnCalificaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCalificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalificacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 480, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
        Login ventanaIniciar = new Login();
        ventanaIniciar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesoresActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        // TODO add your handling code here:
        VAlHorarioAlumno ventanaHorario = new VAlHorarioAlumno();
        ventanaHorario.setVisible(true);
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnTarea1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTarea1ActionPerformed
        // TODO add your handling code here:
        VAlEntregarTarea ventanaTarea = new VAlEntregarTarea();
        ventanaTarea.setVisible(true);
    }//GEN-LAST:event_btnTarea1ActionPerformed

    private void btnCalificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalificacionesActionPerformed
        // TODO add your handling code here:
        VAlCalificaciones ventanaCalif = new VAlCalificaciones();
        ventanaCalif.setVisible(true);
    }//GEN-LAST:event_btnCalificacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAlPaginaPrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAlPaginaPrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAlPaginaPrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAlPaginaPrincipalAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAlPaginaPrincipalAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalificaciones;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnMateria;
    private javax.swing.JButton btnProfesores;
    private javax.swing.JButton btnTarea1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
