/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import javax.swing.JFrame;

/**
 *
 * @author Denis Peralta
 */
public class VPNuevaTarea extends javax.swing.JFrame {

    /**
     * Creates new form NuevaTarea
     */
    public VPNuevaTarea() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        btnAlumno = new javax.swing.JButton();
        btnProfesor = new javax.swing.JButton();
        btnTarea = new javax.swing.JButton();
        btnHorario = new javax.swing.JButton();
        btnMateria = new javax.swing.JButton();
        btnGrupo = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        lblTexto2 = new javax.swing.JLabel();
        lblNTarea = new javax.swing.JLabel();
        txtNombreTarea = new javax.swing.JTextField();
        lblInstrucciones = new javax.swing.JLabel();
        txtInstrucciones = new javax.swing.JTextField();
        btnGenerarIns = new javax.swing.JButton();
        lblGrupo = new javax.swing.JLabel();
        cmbGrupo = new javax.swing.JComboBox<>();
        lblPuntos = new javax.swing.JLabel();
        cmbPuntos = new javax.swing.JComboBox<>();
        lblFechaEntrega = new javax.swing.JLabel();
        cmbFechaEntrega = new javax.swing.JComboBox<>();
        lblTema = new javax.swing.JLabel();
        cmbTema = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Hope logo 13.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        btnAlumno.setBackground(new java.awt.Color(178, 226, 226));
        btnAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/UserCircle.png"))); // NOI18N
        btnAlumno.setText("Alumno");
        btnAlumno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 180, 40));

        btnProfesor.setBackground(new java.awt.Color(178, 226, 226));
        btnProfesor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Profesor.png"))); // NOI18N
        btnProfesor.setText("Profesor");
        btnProfesor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnProfesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 180, 40));

        btnTarea.setBackground(new java.awt.Color(178, 226, 226));
        btnTarea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Tarea.png"))); // NOI18N
        btnTarea.setText("Tarea");
        btnTarea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTareaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 180, 40));

        btnHorario.setBackground(new java.awt.Color(178, 226, 226));
        btnHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Calendario.png"))); // NOI18N
        btnHorario.setText("Horario");
        btnHorario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 180, 40));

        btnMateria.setBackground(new java.awt.Color(178, 226, 226));
        btnMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Materia.png"))); // NOI18N
        btnMateria.setText("Materia");
        btnMateria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 180, 40));

        btnGrupo.setBackground(new java.awt.Color(178, 226, 226));
        btnGrupo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/GrupoUsuario.png"))); // NOI18N
        btnGrupo.setText("Grupo");
        btnGrupo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrupoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 180, 40));

        btnCerrarSesion.setBackground(new java.awt.Color(178, 226, 226));
        btnCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Login.png"))); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 580, 180, 40));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("NUEVA TAREA");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, -1));

        lblTexto2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblTexto2.setForeground(new java.awt.Color(153, 153, 153));
        lblTexto2.setText("Complete la información con los datos de la tarea");
        getContentPane().add(lblTexto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, -1, 20));

        lblNTarea.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblNTarea.setForeground(new java.awt.Color(153, 153, 153));
        lblNTarea.setText("Nombre de la tarea");
        getContentPane().add(lblNTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 350, 30));

        txtNombreTarea.setForeground(new java.awt.Color(204, 204, 204));
        txtNombreTarea.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtNombreTarea, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 600, 40));

        lblInstrucciones.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblInstrucciones.setForeground(new java.awt.Color(153, 153, 153));
        lblInstrucciones.setText("Instrucciones de la tarea");
        getContentPane().add(lblInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 370, 30));

        txtInstrucciones.setForeground(new java.awt.Color(204, 204, 204));
        txtInstrucciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(txtInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 600, 40));

        btnGenerarIns.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerarIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/pdf.png"))); // NOI18N
        btnGenerarIns.setText("Generar (instrucciones) PDF");
        btnGenerarIns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarInsActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 240, 40));

        lblGrupo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblGrupo.setForeground(new java.awt.Color(153, 153, 153));
        lblGrupo.setText("Grupo");
        getContentPane().add(lblGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 190, 150, 30));

        cmbGrupo.setForeground(new java.awt.Color(153, 153, 153));
        cmbGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grupo", "Grupo1", "Grupo2", "Grupo3", "Grupo4", "Grupo5", "Grupo6" }));
        getContentPane().add(cmbGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 220, 200, 40));

        lblPuntos.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(153, 153, 153));
        lblPuntos.setText("Puntos");
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 280, 150, 30));

        cmbPuntos.setForeground(new java.awt.Color(153, 153, 153));
        cmbPuntos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Puntos" }));
        getContentPane().add(cmbPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 310, 190, 40));

        lblFechaEntrega.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblFechaEntrega.setForeground(new java.awt.Color(153, 153, 153));
        lblFechaEntrega.setText("Fecha de entrega");
        getContentPane().add(lblFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 370, 210, 30));

        cmbFechaEntrega.setForeground(new java.awt.Color(153, 153, 153));
        cmbFechaEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fecha de entrega", " " }));
        getContentPane().add(cmbFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, 300, 40));

        lblTema.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblTema.setForeground(new java.awt.Color(153, 153, 153));
        lblTema.setText("Tema");
        getContentPane().add(lblTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 460, 140, 30));

        cmbTema.setForeground(new java.awt.Color(153, 153, 153));
        cmbTema.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tema" }));
        getContentPane().add(cmbTema, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 250, 40));

        btnVolver.setBackground(new java.awt.Color(204, 204, 204));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Volver.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 660, 120, 30));

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Eliminar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 660, 120, 30));

        btnCrear.setBackground(new java.awt.Color(204, 204, 204));
        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Desing/Añadir.png"))); // NOI18N
        btnCrear.setText("Crear tarea");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 660, 120, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlumnoActionPerformed

    private void btnProfesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProfesorActionPerformed

    private void btnTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTareaActionPerformed

    private void btnHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHorarioActionPerformed

    private void btnMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMateriaActionPerformed

    private void btnGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGrupoActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnGenerarInsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarInsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGenerarInsActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VPNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VPNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VPNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VPNuevaTarea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VPNuevaTarea().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlumno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGenerarIns;
    private javax.swing.JButton btnGrupo;
    private javax.swing.JButton btnHorario;
    private javax.swing.JButton btnMateria;
    private javax.swing.JButton btnProfesor;
    private javax.swing.JButton btnTarea;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbFechaEntrega;
    private javax.swing.JComboBox<String> cmbGrupo;
    private javax.swing.JComboBox<String> cmbPuntos;
    private javax.swing.JComboBox<String> cmbTema;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblInstrucciones;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNTarea;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblTema;
    private javax.swing.JLabel lblTexto2;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtInstrucciones;
    private javax.swing.JTextField txtNombreTarea;
    // End of variables declaration//GEN-END:variables
}
